language: node_js

node_js:
  - "node"
  - "lts/*"
  - "7"

notifications:
  email: false

sudo: false

install:
  - npm install

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g gulp-cli

script:
  - npm run build