language: node_js

node_js:
  - "node"
  - "lts/*"
  - "7"

notifications:
  email: false

sudo: required

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - yarn install

cache:
  yarn: true
  directories:
    - "node_modules"

before_script:
  - yarn global add gulp-cli

script:
  - yarn --version
  - npm run build
